name: halftone
base: core24
adopt-info: halftone
compression: lzo
grade: stable
confinement: strict

parts:  
  libjxl:
    source: https://github.com/libjxl/libjxl.git
    source-tag: 'v0.10.2'
    plugin: cmake
    source-depth: 1
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_TESTING=OFF
      - -DJPEGXL_ENABLE_BENCHMARK=OFF
      - -DJPEGXL_ENABLE_DOXYGEN=OFF
      - -DJPEGXL_ENABLE_EXAMPLES=OFF
      - -DJPEGXL_ENABLE_JNI=OFF
      - -DJPEGXL_ENABLE_JPEGLI_LIBJPEG=OFF
      - -DJPEGXL_ENABLE_MANPAGES=OFF
      - -DJPEGXL_ENABLE_PLUGINS=OFF
      - -DJPEGXL_ENABLE_SJPEG=ON
      - -DJPEGXL_ENABLE_SKCMS=ON
      - -DJPEGXL_ENABLE_TOOLS=OFF
      - -DJPEGXL_FORCE_SYSTEM_BROTLI=ON
      - -DJPEGXL_WARNINGS_AS_ERRORS=OFF
    prime:
      - -usr/include
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/*.a
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/*.la
      - -usr/share

  magick:
    after: [libjxl]
    plugin: autotools
    source: https://github.com/ImageMagick/ImageMagick.git
    source-tag: '7.1.1-26'
    build-packages:
      - libjpeg-dev
      - libopenjp2-7-dev
      - libopenexr-dev
      - libstdc++-14-dev
      - libheif-dev
      - liblcms2-dev
      - liblqr-1-0-dev
      - libraw-dev
      - libwmf-dev
      - libzip-dev
      - libzstd-dev
      - libraqm-dev
    build-environment:
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
    source-depth: 1
    autotools-configure-parameters:
      - --prefix=/usr
      - --with-heic=yes
      - --with-rsvg=yes
      - --disable-docs
    prime:
      - -usr/lib/*/pkgconfig
      - -usr/lib/*/*.la
      - -usr/lib/*/*.a
      - -usr/include
    organize:
      usr/etc: usr/share

  halftone:
    after: [ magick ]
    plugin: meson
    source: https://github.com/tfuxu/Halftone.git
    source-tag: '0.6.1'
    source-depth: 1
    meson-parameters:
      - --prefix=/snap/halftone/current/usr
      - -Dbuildtype=release 
    build-snaps:
      - blueprint-compiler/latest/edge 
    override-build: |
      craftctl default
      sed -i '1c#!/usr/bin/env python3' $CRAFT_PART_INSTALL/snap/halftone/current/usr/bin/halftone
    parse-info: [usr/share/appdata/io.github.tfuxu.Halftone.appdata.xml]
    organize:
      snap/halftone/current: .
    prime:
      - -snap/halftone

  deps:
    after: [ halftone ]
    plugin: python
    source: .
    python-packages:
      - Wand==0.6.13
    stage-packages:
      - liblqr-1-0
      - libraw23t64
      - libopenexr-3-1-30
      - libheif1
      - libjpeg62
      - libwmf0.2-7
      - libzip4t64
      - libzstd1
      - libraqm0
    prime:
      - -bin
      - -pyvenv.cfg
      - -include
      - -lib64
      - -lib
      - -usr/lib/*/*/pip*
      - -usr/lib/*/*/setup*
      - -usr/share
    organize:
      lib/python3.12/site-packages: usr/lib/python3/dist-packages

  cleanup:
    after:
    - deps
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core24
      - gnome-46-2404
    override-prime: |
      set -eux
      for snap in "core24" "gnome-46-2404"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "$CRAFT_PRIME/{}" \;
      done

slots:
  halftone:
    interface: dbus
    bus: session
    name: io.github.tfuxu.Halftone

apps:
  halftone:
    command: usr/bin/halftone
    common-id: io.github.tfuxu.Halftone
    extensions: [gnome]
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      GDK_DEBUG: portals
      MAGICK_CONFIGURE_PATH: $SNAP/usr/share/ImageMagick-7
      MAGICK_HOME: $SNAP/usr
    plugs:
      - home
    
      
