name: halftone # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: halftone
version: '0.2.0'
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:      
  halftone:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/tfuxu/Halftone.git
    source-tag: '0.2.1'
    meson-parameters:
      - --prefix=/snap/halftone/current/usr
      - -Dbuildtype=release
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/halftone.patch
      pip install --prefix=$CRAFT_PART_INSTALL/usr Wand==0.6.11
      pip install --prefix=$CRAFT_PART_INSTALL/usr libtiff
    build-packages:
      - blueprint-compiler
    stage-packages:
      - libmagickwand-6.q16-6
      - libtiff5
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/halftone/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    override-prime: |
      craftctl default
      if [ "$CRAFT_ARCH_TRIPLET" = "arm-linux-gnueabihf" ]; then
      execstack --clear-execstack usr/lib/arm-linux-gnueabihf/libde265.so.0.1.1
      fi
    parse-info: [usr/share/appdata/io.github.tfuxu.Halftone.appdata.xml]
    organize:
      snap/halftone/current: .
      usr/local: usr
    prime:
      - -usr/share/doc
slots:
  halftone:
    interface: dbus
    bus: session
    name: io.github.tfuxu.Halftone
apps:
  halftone:
    command: usr/bin/halftone
    common-id: io.github.tfuxu.Halftone
    extensions: [gnome]
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.10/dist-packages:$PYTHONPATH
    plugs:
      - home
    
      
